### ISSUE TITLE
Problem about `cwd` and `perltidy-more.executable`

### ISSUE THREAD

**Issue by hitode909** [kak-tus/perltidy-more#9]
Hi! Thank you for great plugin, I'm using this plugin everyday.

Recently, I'm trying to call perltidy on docker from perltidy-more on host machine.
My approach is below.

1. Prepare a wrapper script to run perltidy on docker.

```bash
% cat script/docker/perltidy
#!/bin/bash
exec docker run -i -v "$PWD":/app -w /app avastsoftware/perltidy $@
```

2. Set `perltidy-more.excutable` to the wrapper script.

```json
"perltidy-more.executable": "./script/docker/perltidy"
```

But it fails. This is because, perltidy-more set cwd to `dirname(document.uri.fsPath)` and `./script/docker/perltidy` is not found from source code's dirname.
- https://github.com/kak-tus/perltidy-more/blob/master/src/extension.ts#L50

I have two solutions to fix this problem.

1. Always set `cwd` to `.`.
  - I think this is simple.
2. Implement a setting to specify cwd, like `"perltidy-more.cwd": "."`.
  - This is complicated to use. I don't know there is another use-case to set cwd.

What do you think?
Thank you.

**Comment by kak-tus** [comment]
Is it a good idea to use relative path to perltidy wrapper? Because it depends from project in vscode. So, if you set it for one project, it can't work in another project.

Main idea was, that perltidy binary/script (or wrapper in your case) is placed in some system folder and accessible thru $PATH or with absolute link in perltidy-more.excutable.

But if relative path to wrapper is important for you - I can easily fix this with checking path from perltidy-more.excutable to absolute/relative and searching it in current project/workspace folder.

**Comment by hitode909** [comment]
Setting relative path is meaningful for me. My project repository has workspace settings. It includes `.vscode` directory and share workspace settings.
- https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings

If I can use a  wrapper script, other developers don't need to include Perl::Tidy, they will be able to just run perltidy on docker.

> checking path from perltidy-more.excutable to absolute/relative and searching it in current project/workspace folder.

This looks good! I tried your approach at #10, it works fine.

**Comment by kak-tus** [comment]
Ready. Thank you!

**Comment by hitode909** [comment]
Thank you so much!
